services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tincan
      - MYSQL_DATABASE=tincan
      - MYSQL_USER=tincan
      - MYSQL_PASSWORD=tincan
    expose:
      - 3306
      - 33060
  web:
    depends_on:
      - db
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - TC_BASE_PATH=/var/www/html
      - TC_UPLOADS_PATH=/var/www/html/uploads
      - TC_DB_HOST=db
      - TC_DB_USER=tincan
      - TC_DB_PASS=tincan
      - TC_DB_NAME=tincan
      - TC_DB_PORT=3306
volumes:
  db_data:
